#!/usr/bin/env zsh

TRUFFLE=~/work/truffle/packages/core/cli.js
# ts on os x: brew install task-spooler
# tsp on linux
if command -v tsp &> /dev/null; then
  TASKSPOOLER=tsp
  echo "Using tsp"
elif command -v ts &> /dev/null; then
  TASKSPOOLER=ts
  echo "Using ts"
fi

HTTP=http://$(
  git remote -v | grep origin | head -n 1 | sed 's:git@::' | sed 's:\.git::' | awk '{ print $2 }' | sed 's:\::/:'
)
COMMIT=$(git rev-parse HEAD)
GH_BASE="${HTTP}/blob/${COMMIT}/"

## clear out txns.out
rm txns.out
mkdir truffle-seq

for folder in $(find ./test -mindepth 1 -maxdepth 2 -type d); do
  for test in $(ls $folder/test_*.js); do
    md_out="truffle-seq/${folder:t}_${test:t:r:l}.md"

    ## start ganache
    proc=$(${TASKSPOOLER} ganache-cli --noVMErrorsOnRPCResponse -l 10000000)
    sleep 1

    ## run tests
     node ${TRUFFLE} test ${test}

    ## generate
    ./scripts/gen-umls && ./scripts/gen-md.awk txns.out ${md_out} ${GH_BASE}

    ## kill ganache
    ${TASKSPOOLER} -k $proc

    ## clear out txns.out
    rm txns.out
  done
done
